### ISSUE TITLE
Add topic so your project is listed.

### ISSUE THREAD

**Issue by justinmeiners** [robmorgan/go-lc3-vm#1]
Hello,

I hope you enjoyed our tutorial.
Previously your project was listed on the page,
but since we have received so many we are changing the tutorial
to link to topics and languages on GitHub, instead of listing them all individually.

If you want your project to appear in the list, please add the GitHub topic "lc3" to your project.

Thanks for your work!
Justin Meiners (lc3-vm author)

**Comment by robmorgan** [comment]
@justinmeiners sure! Added `lc3`.
